-- ObaidGPT local schema (clean, no pg_dump meta commands)

CREATE TABLE IF NOT EXISTS public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(50) NOT NULL UNIQUE,
    email character varying(255) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.conversations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title character varying(100) DEFAULT 'New Chat'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS public.messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id integer NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
    role character varying(20) NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT messages_role_check CHECK (
        (role)::text = ANY (
            (ARRAY['user'::character varying, 'assistant'::character varying])::text[]
        )
    )
);
