"""initial schema

Revision ID: 6deddc0417c0
Revises: 
Create Date: 2026-07-25 17:05:26.372318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6deddc0417c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('letter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('graded', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('incomplete', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_created_at'), 'grades', ['created_at'], unique=False)
    op.create_index(op.f('ix_grades_dimension'), 'grades', ['dimension'], unique=False)
    op.create_index(op.f('ix_grades_project_id'), 'grades', ['project_id'], unique=False)
    op.create_index(op.f('ix_grades_run_id'), 'grades', ['run_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_kind', sa.String(), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pack_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=False),
    sa.Column('rule_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('rate_limits',
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bucket', 'day')
    )
    op.create_table('runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_set_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_created_at'), 'runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_index(op.f('ix_runs_test_set_version'), 'runs', ['test_set_version'], unique=False)
    op.create_index('runs_claimable', 'runs', ['status', 'leased_until'], unique=False)
    op.create_table('test_sets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_sets_project_id'), 'test_sets', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_sets_version'), 'test_sets', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_sets_version'), table_name='test_sets')
    op.drop_index(op.f('ix_test_sets_project_id'), table_name='test_sets')
    op.drop_table('test_sets')
    op.drop_index('runs_claimable', table_name='runs')
    op.drop_index(op.f('ix_runs_test_set_version'), table_name='runs')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_created_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_grades_run_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_project_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_dimension'), table_name='grades')
    op.drop_index(op.f('ix_grades_created_at'), table_name='grades')
    op.drop_table('grades')
    # ### end Alembic commands ###
