"""Auth.js identity tables

Hand-authored rather than autogenerated: these tables are owned by Auth.js on the
frontend, not by SQLModel, and their column names are fixed by the adapter (camelCase
and quoted, which is unusual for Postgres but not ours to change).

Keeping them in the same migration system is deliberate. Two systems pointing at one
database is a worse problem than the slight oddity of the backend creating tables it
never reads, and it means a deploy applies the whole schema with no manual SQL step.

Ids are text with a server-side default, because the adapter inserts a user without
supplying one, and because `projects.user_id` is text - a uuid column here would make
every join a cast.

Revision ID: 7a1c4d2b9e01
Revises: 6deddc0417c0
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7a1c4d2b9e01"
down_revision: str | None = "6deddc0417c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ID_DEFAULT = sa.text("replace(gen_random_uuid()::text, '-', '')")


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Text(), server_default=_ID_DEFAULT, primary_key=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("emailVerified", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
    )
    op.create_index("users_email", "users", ["email"], unique=True)

    op.create_table(
        "accounts",
        sa.Column("id", sa.Text(), server_default=_ID_DEFAULT, primary_key=True),
        sa.Column("userId", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("providerAccountId", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("id_token", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("session_state", sa.Text(), nullable=True),
        sa.Column("token_type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
    )
    # One GitHub identity maps to one account row; without this a duplicated
    # callback could create a second link for the same person.
    op.create_index(
        "accounts_provider_account",
        "accounts",
        ["provider", "providerAccountId"],
        unique=True,
    )

    op.create_table(
        "sessions",
        sa.Column("id", sa.Text(), server_default=_ID_DEFAULT, primary_key=True),
        sa.Column("userId", sa.Text(), nullable=False),
        sa.Column("expires", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sessionToken", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["userId"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("sessions_token", "sessions", ["sessionToken"], unique=True)

    op.create_table(
        "verification_token",
        sa.Column("identifier", sa.Text(), nullable=False),
        sa.Column("expires", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("identifier", "token"),
    )


def downgrade() -> None:
    op.drop_table("verification_token")
    op.drop_index("sessions_token", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("accounts_provider_account", table_name="accounts")
    op.drop_table("accounts")
    op.drop_index("users_email", table_name="users")
    op.drop_table("users")
